/** Isomorphic public GenUI contracts and implementation. */

export {
  jsonByteLength,
  type ReadUiActionOptions,
  readUiAction,
  readUiActionText,
  sandboxAction,
  UI_ACTION_MAX_BYTES,
  type UiAction,
  type UiActionMessage,
  type UiActionSource,
  uiActionSummary,
  uiActionText,
  validateUiActionContext,
} from './actions.js';
export {
  negotiateCatalog,
  type PreparedUiEmission,
  prepareUiEmission,
  type UiCapabilities,
  validateUiCapabilities,
} from './capabilities.js';
export {
  type Catalog,
  type CatalogOptions,
  COMPONENT_NAME,
  type ComponentDefinition,
  type DefineComponentExtras,
  defineCatalog,
  defineComponent,
  type GenuiStreaming,
  toolNameFor,
  toSnakeCase,
} from './catalog.js';
export {
  assertGenuiChannels,
  type ChannelComponentInput,
  type ChannelConversion,
  type ChannelNativeButton,
  type ChannelNativeImage,
  type ChannelNativeList,
  type ChannelNativeListItem,
  type ChannelNativeMessage,
  type ChannelRenderedMessage,
  type ChartImageRenderer,
  type ComponentChannels,
  canRenderOnChannel,
  channelButtonAction,
  channelCatalog,
  channelInstructions,
  DEFAULT_CHANNEL,
  type GenuiChannelBase,
  type GenuiChannelMode,
  type GenuiChannelOptions,
  type GenuiChannelRender,
  type GenuiChannels,
  isMessagingChannel,
  MESSAGING_CHANNELS,
  type ResolvedGenuiChannel,
  renderChannelMessages,
  resolveGenuiChannel,
  textToHtml,
  turnChannel,
  WEB_CHANNEL,
} from './channels.js';
export {
  type GenuiPartialElement,
  type PartialTreeOptions,
  partialTree,
  treeNodeId,
} from './progressive.js';
export {
  type ChartProps,
  type ComponentFactory,
  type ComponentManifest,
  type ComponentPresentation,
  type ComponentRegistry,
  type ComponentRenderer,
  chart,
  createComponent,
  createComponentRegistry,
  snapshotComponentPresentation,
  type TableCell,
  type TableProps,
  table,
  validatePresentationBatch,
} from './registry.js';
export {
  assertSandboxPolicy,
  buildSandboxDocument,
  type DefineSandboxOptions,
  defineSandbox,
  previewHtml,
  SANDBOX_COMPONENT,
  SANDBOX_DEFAULTS,
  SANDBOX_FIELD_ORDER,
  SANDBOX_IFRAME_FLAGS,
  SANDBOX_MESSAGE,
  Sandbox,
  type SandboxDefinition,
  type SandboxDocumentOptions,
  type SandboxKitSource,
  type SandboxPolicy,
  type SandboxProps,
  type SandboxThemeSource,
  type SandboxView,
  sandboxCsp,
  sandboxPartialProps,
  sandboxPolicyOf,
} from './sandbox.js';
export { prepareSandboxJsx, transpileJsx } from './sandbox-jsx.js';
export {
  kitDocsToModelText,
  kitJsxInstructions,
  SANDBOX_ASSET_SIZES,
  type SandboxClientConfig,
  type SandboxKitComponentDoc,
  type SandboxKitDescriptor,
  type SandboxKitDocs,
  type SandboxKitPropDoc,
  sandboxJsxRuntime,
  tailwindInstructions,
} from './sandbox-kit.js';
export {
  collectHostThemeVars,
  hostThemeCss,
  isColorValue,
  isHostDark,
  isHslChannels,
  type ThemeTokens,
  tailwindThemeCss,
  themeTokens,
  themeToModelText,
  themeVarsFromCss,
  watchHostTheme,
} from './sandbox-theme.js';
export {
  type AjvLike,
  ajvValidator,
  builtinJsonSchemaValidator,
  formatIssues,
  type GenuiIssue,
  type GenuiValidation,
  isStandardSchema,
  type JsonSchema,
  type JsonSchemaValidator,
  type PropsSchema,
  toJsonSchema,
  validateProps,
  validatePropsSync,
} from './schema.js';
export {
  type CatalogTextOptions,
  catalogToModelText,
  componentToText,
  fillTemplate,
  getPath,
  summarizeSchema,
  treeToText,
} from './text.js';
export {
  GENUI_SHOW_TOOL,
  type GenuiCatalogScope,
  type GenuiTool,
  type GenuiToolOutput,
  type GenuiToolsOptions,
  genuiTools,
  jsonStandardSchema,
  type ResolveGenuiCatalog,
  showToolJsonSchema,
} from './tools.js';
export {
  type FlatSpec,
  GENUI_TREE_COMPONENT,
  type GenuiElement,
  type GenuiTreeProps,
  normalizeTreeInput,
  type TreeLimits,
  type TreeSchemaMode,
  treeJsonSchema,
  treeToFlatSpec,
  validateTree,
} from './tree.js';
